#!/bin/sh

for dir in *; do
    cd $dir
        echo -n "${dir}: "
        $@ || exit 1
        #|while read someline; do
        #    echo -n "${mod}: "
        #    echo -e "$someline"
        #done
    cd ..
done

echo
