#!/usr/bin/zsh

export PAGER=less
export CVS_RSH=ssh

export PATH=$PATH:~/.bin



export SCREEN_CAPTION_COLOR="`hostname |md5sum |head -c 1 |tr 0123456789abcdef YRGBCYMRGBCMYRGB`"
# case "`hostname |md5sum |head -c 5|tail --bytes=1|tr 0123456789abcdef YRGBCYMRGBCMYRGB`" in
#   R)
#         prompt oliver red
# 	;;
#   G)
#         prompt oliver green
# 	;;
#   B)
#         prompt oliver blue
# 	;;
#   C)
#         prompt oliver cyan
# 	;;
#   M)
#         prompt oliver magenta
# 	;;
#   Y)
#         prompt oliver yellow
# 	;;
# esac


export TIMEFMT="%U user %S system %P cpu %*E total, running %J"
export COLORTERM=yes

eval $(lessfile)
eval $(dircolors)
export LESSCHARSET=UTF-8
export LESS='-iFRSX'

alias ls='ls --color=auto --classify'


SSH_ASKPASS=`which ssh-askpass`
[[ $? = 0 ]] && export SSH_ASKPASS


